/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DmtUfMO6nA8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Github } from "lucide-react";
import Link from "next/link";
export default function LoginPage() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 p-4">
      <Card className="w-full max-w-md">
        <CardContent className="pt-6">
          <div className="text-center">
            <h1 className="mt-4 mb-8 text-4xl font-semibold text-success">
              Welcome Back
            </h1>
            <p className="text-muted-foreground">
              Login to continue
            </p>
            <Link
              href={`https://github.com/login/oauth/authorize?client_id=${process.env.GITHUB_CLIENT_ID}&redirect_uri=${process.env.GITHUB_REDIRECT_URI}`}
            >
              <Button className="mt-4" variant="secondary">
                <Github className="mr-2 h-5 w-5" />
                Sign in with Github
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
